name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Accept Android SDK Licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev mesa-utils
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          pip install flet
          pip install -r requirements.txt
        
      # MAGIC FIX: Ek single 'y' bheja hai jisse Flet apna private Flutter khud install karega bina error ke
      - name: Build APK with Flet
        run: echo "y" | flet build apk
        
      - name: Upload APK File
        uses: actions/upload-artifact@v4
        with:
          name: ToDo-App-APK
          path: build/apk/**/*.apk

          
